# Generated by Django 3.2.6 on 2021-08-07 13:18

from django.db import migrations, models
import django.db.models.deletion
import mdscheck.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MdsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdf', validators=[mdscheck.validators.validate_file_extension])),
                ('is_donor', models.BooleanField(choices=[(True, 'donor'), (False, 'patient')], default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'CD13_vs_CD11b'), (2, 'CD13_vs_CD16'), (3, 'CD11b_vs_CD16')], default=None, max_length=1)),
                ('image', models.URLField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mdscheck.mdsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('pos', 'abnormal'), ('neg', 'normal'), ('na', 'no idea'), ('pnh', 'PNH')], default='na', max_length=3)),
                ('is_expert', models.BooleanField(default=False)),
                ('responder', models.CharField(choices=[('exp', 'expert'), ('bio', 'biologist'), ('md', 'doctor'), ('nov', 'novice')], default='bio', max_length=3)),
                ('responder_email', models.EmailField(default='', max_length=254)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='mdscheck.images')),
            ],
        ),
    ]
