# Generated by Django 3.2.6 on 2021-08-13 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mdscheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
