# Generated by Django 3.2.6 on 2021-08-14 07:44

from django.db import migrations, models
import mdscheck.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mdscheck', '0002_decision_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdsmodel',
            name='pdf_file',
            field=models.FileField(unique=True, upload_to='pdf', validators=[mdscheck.validators.validate_file_extension]),
        ),
    ]
