# Generated by Django 3.2.6 on 2021-08-16 17:08

from django.db import migrations, models
import mdscheck.models


class Migration(migrations.Migration):

    dependencies = [
        ('mdscheck', '0003_alter_mdsmodel_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdsmodel',
            name='number',
            field=models.IntegerField(),
        ),
    ]
