# Generated by Django 3.2.6 on 2021-08-24 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdscheck', '0006_auto_20210820_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mdsmodel',
            options={'ordering': ['-number']},
        ),
    ]
