# Generated by Django 3.2.6 on 2021-08-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdscheck', '0007_alter_mdsmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='decision',
            field=models.CharField(choices=[('pos', 'Аномальный'), ('neg', 'Нормальный'), ('na', 'Не знаю'), ('pnh', 'ПНГ-клон')], default='na', max_length=3),
        ),
        migrations.AlterField(
            model_name='decision',
            name='responder',
            field=models.CharField(choices=[('exp', 'Эксперт-цитометрист'), ('bio', 'Биолог'), ('md', 'Врач'), ('nov', 'Новичек')], default='bio', max_length=3),
        ),
    ]
